name: treatment_checkup_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.15.5+2
  auto_size_text: ^2.1.0
  google_fonts: ^0.3.9
  menu_button: "0.1.0+1"
  pin_code_fields: ^2.4.0
  percent_indicator: "^2.1.1"
  expandable: ^4.1.2
  flutter_swiper: ^1.1.6
  states_rebuilder: ^1.14.3
  shared_preferences: ^0.5.6+3
  barcode_scan: ^2.0.1
  flutter_spinkit: ^4.1.2+1
  flutter_cupertino_date_picker: ^1.0.26+2
  firebase_storage: ^3.1.5
  image_picker: ^0.6.4
  cached_network_image: ^2.0.0
  file_picker: ^1.6.2
  flutter_phoenix: ^0.1.0
  intl: ^0.16.0   #16.1
  flutter_calendar_carousel: ^1.4.12
  some_calendar: ^1.2.2
  google_maps_flutter: ^0.5.26
  google_map_location_picker: ^3.2.1+2
  slide_popup_dialog: ^0.0.2
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.19.0
  youtube_player_flutter: ^7.0.0+7
  flutter_tts: ^2.1.0
  page_transition: "^1.1.7+6"
  html_unescape: ^1.0.1+3
  collection: ^1.14.13
  async: ^2.4.2
  flutter_launcher_icons: ^0.8.1
dependency_overrides:
  flutter_svg: ^0.18.1
  flutter_cupertino_date_picker:
    git:
      url: https://github.com/arbyazra123/flutter-cupertino-date-picker.git
      ref: updatedDiagnosticable

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/knee_logo.png"
  adaptive_icon_background: "#ffffff"
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
#    - assets/google_fonts/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
